---
# tasks file for python3-pip

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install python3 and pip3
  apt:
    pkg:
    - python3
    - python3-pip
    state: "present"
    update_cache: true
    install_recommends: true
  tags:
  - install