- name: Configure images for VM
  hosts: all
  become: true
  vars:
    pip_install_packages:
      - name: docker

  roles:
    - python3_pip
    - geerlingguy.pip
    - geerlingguy.docker
    - gitlab_ci_docker
