apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: {{ template "ui.fullname" . }}
    servicePort: {{ .Values.service.externalPort }}
