version: '3.3'

services:
  mongodb:
    image: mongo:${mongodb_v}
    container_name: reddit-mongodb
    volumes:
     - mongodb:/data/db
    networks:
      mongodb:
        aliases:
         - post_db
         - comment_db
         - exporter_db

  ui:
    image: ${USERNAME}/ui:${ui_v}
    container_name: reddit-ui
    ports:
     - ${ui_port}:9292/tcp
    networks:
      reddit:
        aliases:
         - ui

  post:
    image: ${USERNAME}/post:${post_v}
    container_name: reddit-post
    networks:
      mongodb: {}
      reddit:
        aliases:
         - post

  comment:
    image: ${USERNAME}/comment:${comment_v}
    container_name: reddit-comment
    networks:
      mongodb: {}
      reddit:
        aliases:
         - comment

volumes:
  mongodb: {}

networks:
  mongodb:
    name: mongodb-network
  reddit:  
    name: reddit-network
