groups:
  - name: alert.rules
    rules:

    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'

    - alert: HttpRequestsErrorStatusCode
      expr: rate(ui_request_count{http_status=~"^[45].*"}[1m]) > 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} sent a response with an error code {{ $labels.http_status }}, path {{ $labels.path }}'
        summary: 'Instance {{ $labels.instance }} sent a response with an error code {{ $labels.http_status }}, path {{ $labels.path }}'

