{
 "title": "UI_Service_Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Env", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "UI HTTP Requests",
   "type": "graph",
   "description": "UI HTTP requests taht UI service receives",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "UI HTTP Requests with Error status code",
   "type": "graph",
   "description": "UI HTTP Requests with Error status code",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\", kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP Response Time 95%",
   "type": "graph",
   "description": "HTTP Response Time 95%",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket{kubernetes_namespace=~\"$namespace\"}[5m])) by (le))"
    }
   ]
  }
 ]
}