---
# tasks file for reddit_in_docker
- name: Start reddit docker container
  docker_container:
    container_default_behavior: no_defaults
    name: reddit
    image: vadimrepo/otus-reddit:1.0
    state: started
    restart_policy: always
    ports:
     - "9292:9292"