Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 512
  end

  config.vm.define "redditserver" do |reddit|
    reddit.vm.box = "ubuntu/xenial64"
    reddit.vm.hostname = "redditserver"
    reddit.vm.network :private_network, ip: "10.10.10.20"
    reddit.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/packer_raddit_in_docker.yml"
    end
  end
end

